# MarsPro Home Assistant Configuration Example
# Place this in your configuration.yaml or use as a separate file

# Advanced configuration
marspro:
  email: "your_email@example.com"
  password: "your_password"
  use_cloud: false
  ble_mac: "A0:B1:C2:D3:E4:F5"
  scan_interval: 30
  
  # Device-specific settings
  devices:
    - name: "Living Room Lamp"
      ble_mac: "A0:B1:C2:D3:E4:F5"
      device_type: "light"
      room: "Living Room"
      
    - name: "Bedroom Fan"
      ble_mac: "B1:C2:D3:E4:F5:A0"
      device_type: "fan"
      room: "Bedroom"
      
  # API settings (if using cloud)
  api:
    base_url: "https://api.marspro.com"
    timeout: 30
    retry_attempts: 3
    
  # BLE settings
  ble:
    timeout: 10
    retry_attempts: 3
    connection_timeout: 5

# Example automation
automation:
  - alias: "Turn on MarsPro lamp at sunset"
    trigger:
      platform: sun
      event: sunset
    action:
      - service: light.turn_on
        target:
          entity_id: light.living_room_lamp
        data:
          brightness: 255
          color_temp: 2700

  - alias: "Turn off MarsPro devices at bedtime"
    trigger:
      platform: time
      at: "22:00:00"
    action:
      - service: light.turn_off
        target:
          entity_id: light.living_room_lamp
      - service: fan.turn_off
        target:
          entity_id: fan.bedroom_fan

# Example script
script:
  marspro_movie_mode:
    alias: "MarsPro Movie Mode"
    sequence:
      - service: light.turn_on
        target:
          entity_id: light.living_room_lamp
        data:
          brightness: 50
          color_temp: 2200
      - service: fan.set_speed
        target:
          entity_id: fan.bedroom_fan
        data:
          speed: "low" 